source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.7'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails'
# Automatically add browser specific css prefixes
gem 'autoprefixer-rails'
# Use Twitter Boostrap CSS framework
gem 'twitter-bootstrap-rails', :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# Better form helpers
gem 'simple_form'
# Use Haml for views
gem 'haml'

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails', github: 'joliss/jquery-ui-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'jquery-turbolinks', git: 'git@github.com:kossnocorp/jquery.turbolinks.git'
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin]
group :development do
  gem "better_errors"
end

# Administrate the site from a separate frontend interface
gem 'formtastic', github: 'justinfrench/formtastic'
gem 'activeadmin', github: 'activeadmin'

# Generate fake data for seeding
gem 'faker'

# User Authentication
gem 'devise'
# Pagination
gem 'kaminari'
# Voting
gem 'acts_as_votable', '~> 0.10.0'
# Commenting
gem 'awesome_nested_set'
gem 'acts_as_commentable_with_threading'
